plugins:
  - jekyll-readme-index
  - jekyll-feed
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-spaceship
  - jekyll-default-layout
  - jekyll-seo-tag
  - jekyll-remote-theme

readme_index:
  remove_originals: true
  with_frontmatter: true

jekyll-archives:
  enabled: all

# jekyll-feed
title: Wu Zhenyu's Blog
author: Wu Zhenyu
description: Record valuable and interesting things
url: //Freed-Wu.github.io
