---
"on":
  push:
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        run: >
          curl -X POST -d '{"ref":"main"}'
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"
          https://api.github.com/repos/Freed-Wu/Freed-Wu.github.io/actions/workflows/main.yml/dispatches
      - name: Trigger Workflow
        run: >
          curl -X POST -d '{"ref":"main"}'
          -H "Accept: application/vnd.github.v3+json"
          -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}"
          https://api.github.com/repos/Freed-Wu/Freed-Wu/actions/workflows/jekyll.yml/dispatches
